version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "chore"
      - "safe-to-test"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "src/main/docker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "chore"
      - "safe-to-test"
