pull_request_rules:
  - name: backport patches to cryostat-v2.3 branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - cryostat-v2.3
        assignees:
          - "{{ author }}"
