pull_request_rules:
  - name: backport patches to cryostat-v3.0 branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - cryostat-v3.0
        assignees:
          - "{{ author }}"
