FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:8ff5fdb142dbfc6c86924bdc4387dadc78a0ecbb7aa35e0d20b7d4ba37550e44
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
USER 1001
EXPOSE 8080
ENV LISTEN_HOST=${LISTEN_HOST:-0.0.0.0}
CMD ["./application", "-Dquarkus.http.host=${LISTEN_HOST}"]
