FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:128021168edb5b3013258601a2dffe93fddfed91cf996c08c76a24dfdcd6de13
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
USER 1001
EXPOSE 8080
ENV LISTEN_HOST=${LISTEN_HOST:-0.0.0.0}
CMD ["./application", "-Dquarkus.http.host=${LISTEN_HOST}"]
