FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:e2e7f267999e366c768ff36ff69e8c1cf591375f0f27109535570029d1020784
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
USER 1001
EXPOSE 8080
ENV LISTEN_HOST=${LISTEN_HOST:-0.0.0.0}
CMD ["./application", "-Dquarkus.http.host=${LISTEN_HOST}"]
