{
 "title": "Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "jdk.CPUInformation.cores", "type": "timeserie" }
   ]
  },
  {
   "title": "Hardware Threads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "jdk.CPUInformation.hwThreads", "type": "timeserie" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "target": "jdk.CPULoad.jvmUser", "type": "timeserie" },
    { "target": "jdk.CPULoad.jvmSystem", "type": "timeserie" },
    { "target": "jdk.CPULoad.machineTotal", "type": "timeserie" }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "target": "jdk.GCHeapSummary.heapUsed", "type": "timeserie" }
   ]
  },
  {
   "title": "Used Physical Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "target": "jdk.PhysicalMemory.usedSize", "type": "timeserie" }
   ]
  },
  {
   "title": "Total Physical Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "target": "jdk.PhysicalMemory.totalSize", "type": "timeserie" }
   ]
  },
  {
   "title": "Recording Start Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "target": "jdk.ActiveRecording.recordingStart",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Recording Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "jdk.ActiveRecording.recordingDuration",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ClassLoadingStatistics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jdk.ClassLoadingStatistics.unloadedClassCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.ClassLoadingStatistics.loadedClassCount",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Metaspace Summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "jdk.MetaspaceSummary.metaspace:committed",
     "type": "timeserie"
    },
    {
     "target": "jdk.MetaspaceSummary.metaspace:reserved",
     "type": "timeserie"
    },
    {
     "target": "jdk.MetaspaceSummary.metaspace:used",
     "type": "timeserie"
    },
    {
     "target": "jdk.MetaspaceSummary.dataSpace:committed",
     "type": "timeserie"
    },
    {
     "target": "jdk.MetaspaceSummary.dataSpace:used",
     "type": "timeserie"
    },
    {
     "target": "jdk.MetaspaceSummary.dataSpace:reserved",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "jdk.NetworkUtilization.readRate",
     "type": "timeserie"
    },
    {
     "target": "jdk.NetworkUtilization.writeRate",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Metaspace GC Threshold",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "jdk.MetaspaceGCThreshold.oldValue",
     "type": "timeserie"
    },
    {
     "target": "jdk.MetaspaceGCThreshold.newValue",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Java Thread Statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jdk.JavaThreadStatistics.accumulatedCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.JavaThreadStatistics.activeCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.JavaThreadStatistics.daemonCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.JavaThreadStatistics.peakCount",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Exception Statistics",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jdk.ExceptionStatistics.throwables",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Thread Context Switch Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "jdk.ThreadContextSwitchRate.switchRate",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Compiler Statistics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jdk.CompilerStatistics.compileCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.CompilerStatistics.bailoutCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.CompilerStatistics.invalidatedCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.CompilerStatistics.osrCompileCount",
     "type": "timeserie"
    },
    {
     "target": "jdk.CompilerStatistics.standardCompileCount",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Compiler Peak Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 19 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "jdk.CompilerStatistics.peakTimeSpent",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Safepoint Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "jdk.SafepointBegin.duration", "type": "timeserie" }
   ]
  },
  {
   "title": "File Statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "jdk.FileRead", "type": "timeserie" },
    { "target": "jdk.FileWrite", "type": "timeserie" }
   ]
  },
  {
   "title": "Compiler: Total Time Spent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "jdk.CompilerStatistics.totalTimeSpent",
     "type": "timeserie"
    }
   ]
  }
 ]
}